[package]
name = "rotor-http"
description = """
    The mio-based http server (+with http client and websockets planned)
"""
license = "MIT"
readme = "README.rst"
keywords = ["mio", "http", "websocket", "rotor"]
homepage = "http://github.com/tailhook/rotor-http"
version = "0.3.0"
authors = ["paul@colomiets.name"]

[dependencies]
hyper = "0.6.13"
httparse = "1.0.0"
netbuf = "0.2.0"
log = "0.3.2"
time = "0.1.23"
mio = "0.4.3"
# rotor = "0.4.0"
rotor = { git = "git://github.com/tailhook/rotor", rev = "b6db831" }

[dev-dependencies]
libc = "*"

[lib]
name = "rotor_http"
