[package]
name = "rotor-http"
description = """
    The mio-based http server (+with http client and websockets planned)
"""
license = "MIT"
readme = "README.rst"
keywords = ["mio", "http", "websocket", "rotor"]
homepage = "http://github.com/tailhook/rotor-http"
version = "0.2.1"
authors = ["paul@colomiets.name"]

[dependencies]
hyper = "*"
httparse = "*"
netbuf = "*"
log = "*"
time = "*"
mio = "*"
rotor = "0.2"

[dev-dependencies]
libc = "*"

[lib]
name = "rotor_http"
