[package]
name = "rotor-http"
description = """
    The mio-based http server (+with http client and websockets planned)
"""
license = "MIT"
readme = "README.rst"
keywords = ["mio", "http", "websocket", "rotor"]
homepage = "http://github.com/tailhook/rotor-http"
version = "0.2.2"
authors = ["paul@colomiets.name"]

[dependencies]
hyper = "0.6.13"
httparse = "^0.1"
netbuf = "0.2.0"
log = "*"
time = "*"
mio = "0.4.3"
rotor = "0.2"

[dev-dependencies]
libc = "*"

[lib]
name = "rotor_http"
