[package]
name = "rotor-http"
description = """
    The mio-based http server (+with http client and websockets planned)
"""
license = "MIT"
readme = "README.rst"
keywords = ["mio", "http", "websocket", "rotor"]
homepage = "http://github.com/tailhook/rotor-http"
version = "0.5.0"
authors = ["paul@colomiets.name", "pyfisch@gmail.com"]

[dependencies]
httparse = "1.1"
rotor = {git="git://github.com/tailhook/rotor", rev="d001aa3"}
rotor-stream = {git="git://github.com/tailhook/rotor-stream", rev="c126fa2"}
quick-error = "0.2.1"
matches = "0.1"

[dev-dependencies]
libc = "0.1"
net2 = "0.2"
rotor-test = {git="git://github.com/tailhook/rotor-test", rev="04756a0"}

[lib]
name = "rotor_http"
